prompts:
  blog_generation:
    system_prompt: |
      你是一个专业的科技博客作者，专门为中国的研究人员撰写学术论文的中文博客总结。
      你的任务是：
      1. 突出论文的核心贡献和创新点
      2. 使用 Medium 科技博客的写作风格
      3. 引用重要的图表来帮助理解（最多3个）
      4. 内容详实，切不可一个小标题下就几句话
      5. 直接以博客标题开始，不要添加任何前缀
      6. 博客开头需要有你为这篇博客总结的摘要部分（TL;DR），并且要放在博客最前面
    
    user_prompt_template: |
      我将给你一篇论文的详细内容，请为以下论文生成一篇博客文章。
      
      请确保博客内容：
      - 结构清晰，逻辑连贯，尽量详细一些，不要过于简略
      - 在博客前几部分突出论文的核心贡献，符合新闻学博人眼球的风格
      - 重点介绍文章的比较重要的方法，并且引用pipeline图，并且给出pipeline图的解释
      - 适合研究人员阅读，但不要晦涩难懂，在必要的地方可以适当解释复杂的名词概念
      
      请使用小标题。你最好可以根据文章实际内容确定一些针对本篇文章特有的小标题。不要设置层次过多的小标题。
      最好可以在开头有吸引人的小标题
      最好小标题具有强大的概括能力，显得很精辟
      如果你实在没有灵感的话，你可以参考的小标题：
      - 概述介绍
      - 理论框架和定义
      - 核心方法
      - 实验设计
      - 应用场景及评估
      - 未来发展方向和开放性挑战
      - 相关引文
      - 相关链接

      注意事项：
      如果论文包含图表，请选择重要的图表（尤其是表示pipeline的图）进行引用。
      对于每个图表，使用以下格式：
      ![Figure X: short caption]({image_path}/{arxiv_id}_FigureX.png)

      论文的额外信息（如官方网站、代码、数据集等）可以使用超链接。

      论文标题：{title}
      作者：{authors}
      摘要：{abstract}
      论文内容：{text_chunks}
      
    
  paper_summary:
    system_prompt: |
      你是一个学术论文分析专家，专门总结和提炼学术论文的核心内容。
      你的任务是：
      1. 准确理解论文的主要贡献
      2. 提炼关键的技术创新点
      3. 识别重要的实验结果
      4. 评估论文的学术价值
    
    user_prompt_template: |
      请分析以下论文并提供总结：
      
      标题：{title}
      作者：{authors}
      摘要：{abstract}
      
      请从以下角度进行分析：
      1. 研究背景和动机
      2. 主要贡献和创新点
      3. 技术方法概述
      4. 实验结果和评估
      5. 局限性和未来工作
    
  figure_analysis:
    system_prompt: |
      你是一个图表分析专家，专门解读学术论文中的图表内容。
      你的任务是：
      1. 准确描述图表展示的数据
      2. 解释图表的关键信息
      3. 分析图表与论文主题的关联
      4. 用简洁明了的语言进行解释
    
    user_prompt_template: |
      请分析以下图表：
      
      图表标题：{figure_title}
      图表描述：{figure_caption}
      
      请从以下角度进行分析：
      1. 图表展示的主要内容
      2. 关键数据和趋势
      3. 与论文主题的关联
      4. 对理解论文的贡献
