# 后端API配置

# API服务URL
api_url: "http://localhost:8000/api"

# 测试用户数据
test_user:
  username: "test_user@example.com"
  email: "test_user@example.com"
  password: "TestPassword123"

# 前端URL (用于前端测试)
frontend_url: "http://localhost:3000"

# 数据库配置
# 注意: 以下数据库配置可以通过环境变量覆盖
# 主数据库环境变量: DB_USER, DB_PASSWORD, DB_HOST, DB_PORT, DB_NAME
# 测试数据库环境变量: TEST_DB_USER, TEST_DB_PASSWORD, TEST_DB_HOST, TEST_DB_PORT, TEST_DB_NAME
database:
  # 主数据库配置
  main:
    user: "postgres"
    password: ""
    host: "localhost"
    port: "5432"
    name: "paperignition_user"
  
  # 测试数据库配置
  test:
    user: "postgres"
    password: ""
    host: "localhost"
    port: "5432"
    name: "paperignition_test" 